---
version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ${PWD}/docker/otel-collector.yml:/etc/otel-collector-config.yml
    ports:
      - 4317:4317  # OTLP gRPC receiver
      - 9464:9464  # Prometheus exporter
    networks:
      - otel
    depends_on:
      - zipkin
      - prometheus
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - otel
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/config.yml
    volumes:
      - ${PWD}/docker/prometheus.yml:/etc/prometheus/config.yml
    ports:
      - 9090:9090
    networks:
      - otel
networks:
  otel:
