---
name: ci
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ "{{" }} secrets.CODECOV_TOKEN {{ "}}" }}
          file: /tmp/coverage.txt
      - run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install gotest.tools/gotestsum@latest
      - name: ci
        run: |
          just ci
