---
assert_lefthook_installed: true
colors: false
no_tty: true
skip_output:
  - execution  # Skips printing execution logs (but prints on failure)
  - execution_out  # Skips printing execution output (but prints failure)
  - execution_info  # Skips printing `EXECUTE > ...` logging
pre-commit:
  parallel: true
  commands:
    lint:
      run: just lint
      stage_fixed: true
    test:
      run: just test
